// Generated by gencpp from file slaw_youbot_arm_navigation_actions/MoveArmLinearActionGoal.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMLINEARACTIONGOAL_H
#define SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMLINEARACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <slaw_youbot_arm_navigation_actions/MoveArmLinearGoal.h>

namespace slaw_youbot_arm_navigation_actions
{
template <class ContainerAllocator>
struct MoveArmLinearActionGoal_
{
  typedef MoveArmLinearActionGoal_<ContainerAllocator> Type;

  MoveArmLinearActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  MoveArmLinearActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::slaw_youbot_arm_navigation_actions::MoveArmLinearGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmLinearActionGoal_

typedef ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<std::allocator<void> > MoveArmLinearActionGoal;

typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal > MoveArmLinearActionGoalPtr;
typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal const> MoveArmLinearActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slaw_youbot_arm_navigation_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slaw_youbot_arm_navigation_actions': ['/home/ruud/youBot/devel/share/slaw_youbot_arm_navigation_actions/msg'], 'slaw_youbot_arm_navigation_msgs': ['/home/ruud/youBot/src/slaw_youbot_arm_navigation/slaw_youbot_arm_navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d30939ff45fbd0d89b545a21962c6748";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd30939ff45fbd0d8ULL;
  static const uint64_t static_value2 = 0x9b545a21962c6748ULL;
};

template<class ContainerAllocator>
struct DataType< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_actions/MoveArmLinearActionGoal";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
MoveArmLinearGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: slaw_youbot_arm_navigation_actions/MoveArmLinearGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
slaw_youbot_arm_navigation_msgs/EndeffectorPosition[] points\n\
float32 max_speed\n\
string side\n\
float32 endlink_angle\n\
bool horizontal\n\
float32 endeffector_offset\n\
\n\
================================================================================\n\
MSG: slaw_youbot_arm_navigation_msgs/EndeffectorPosition\n\
geometry_msgs/Point position\n\
float32 angle\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmLinearActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slaw_youbot_arm_navigation_actions::MoveArmLinearActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::slaw_youbot_arm_navigation_actions::MoveArmLinearGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMLINEARACTIONGOAL_H
