// Generated by gencpp from file slaw_youbot_arm_navigation_actions/MoveArmIKFeedback.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMIKFEEDBACK_H
#define SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMIKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slaw_youbot_arm_navigation_actions
{
template <class ContainerAllocator>
struct MoveArmIKFeedback_
{
  typedef MoveArmIKFeedback_<ContainerAllocator> Type;

  MoveArmIKFeedback_()
    {
    }
  MoveArmIKFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmIKFeedback_

typedef ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<std::allocator<void> > MoveArmIKFeedback;

typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback > MoveArmIKFeedbackPtr;
typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback const> MoveArmIKFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slaw_youbot_arm_navigation_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slaw_youbot_arm_navigation_actions': ['/home/ruud/youBot/devel/share/slaw_youbot_arm_navigation_actions/msg'], 'slaw_youbot_arm_navigation_msgs': ['/home/ruud/youBot/src/slaw_youbot_arm_navigation/slaw_youbot_arm_navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_actions/MoveArmIKFeedback";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmIKFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::slaw_youbot_arm_navigation_actions::MoveArmIKFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMIKFEEDBACK_H
