// Generated by gencpp from file slaw_youbot_arm_navigation_actions/MoveArmIKGoal.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMIKGOAL_H
#define SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMIKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace slaw_youbot_arm_navigation_actions
{
template <class ContainerAllocator>
struct MoveArmIKGoal_
{
  typedef MoveArmIKGoal_<ContainerAllocator> Type;

  MoveArmIKGoal_()
    : position()
    , angle(0.0)
    , side()
    , velocity_controlled(false)
    , endlink_angle(0.0)
    , horizontal(false)
    , endeffector_offset(0.0)
    , max_speed(0.0)  {
    }
  MoveArmIKGoal_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , angle(0.0)
    , side(_alloc)
    , velocity_controlled(false)
    , endlink_angle(0.0)
    , horizontal(false)
    , endeffector_offset(0.0)
    , max_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _angle_type;
  _angle_type angle;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _side_type;
  _side_type side;

   typedef uint8_t _velocity_controlled_type;
  _velocity_controlled_type velocity_controlled;

   typedef float _endlink_angle_type;
  _endlink_angle_type endlink_angle;

   typedef uint8_t _horizontal_type;
  _horizontal_type horizontal;

   typedef float _endeffector_offset_type;
  _endeffector_offset_type endeffector_offset;

   typedef float _max_speed_type;
  _max_speed_type max_speed;




  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmIKGoal_

typedef ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<std::allocator<void> > MoveArmIKGoal;

typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal > MoveArmIKGoalPtr;
typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal const> MoveArmIKGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slaw_youbot_arm_navigation_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slaw_youbot_arm_navigation_actions': ['/home/ruud/youBot/devel/share/slaw_youbot_arm_navigation_actions/msg'], 'slaw_youbot_arm_navigation_msgs': ['/home/ruud/youBot/src/slaw_youbot_arm_navigation/slaw_youbot_arm_navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a94cf100fc9942d638bc51be7b67ca2";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a94cf100fc9942dULL;
  static const uint64_t static_value2 = 0x638bc51be7b67ca2ULL;
};

template<class ContainerAllocator>
struct DataType< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_actions/MoveArmIKGoal";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
geometry_msgs/Point position\n\
float32 angle\n\
string side\n\
bool velocity_controlled\n\
float32 endlink_angle\n\
bool horizontal\n\
float32 endeffector_offset\n\
float32 max_speed\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle);
      stream.next(m.side);
      stream.next(m.velocity_controlled);
      stream.next(m.endlink_angle);
      stream.next(m.horizontal);
      stream.next(m.endeffector_offset);
      stream.next(m.max_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmIKGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slaw_youbot_arm_navigation_actions::MoveArmIKGoal_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "side: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.side);
    s << indent << "velocity_controlled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.velocity_controlled);
    s << indent << "endlink_angle: ";
    Printer<float>::stream(s, indent + "  ", v.endlink_angle);
    s << indent << "horizontal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.horizontal);
    s << indent << "endeffector_offset: ";
    Printer<float>::stream(s, indent + "  ", v.endeffector_offset);
    s << indent << "max_speed: ";
    Printer<float>::stream(s, indent + "  ", v.max_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_ACTIONS_MESSAGE_MOVEARMIKGOAL_H
