// Generated by gencpp from file slaw_youbot_arm_navigation_srvs/MoveArm.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_MOVEARM_H
#define SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_MOVEARM_H

#include <ros/service_traits.h>


#include <slaw_youbot_arm_navigation_srvs/MoveArmRequest.h>
#include <slaw_youbot_arm_navigation_srvs/MoveArmResponse.h>


namespace slaw_youbot_arm_navigation_srvs
{

struct MoveArm
{

typedef MoveArmRequest Request;
typedef MoveArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveArm
} // namespace slaw_youbot_arm_navigation_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArm > {
  static const char* value()
  {
    return "9f106f1e1533bc6bfe2e5855c5cd2307";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArm&) { return value(); }
};

template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::MoveArm > {
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_srvs/MoveArm";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArm&) { return value(); }
};


// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmRequest> should match 
// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArm > 
template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArm >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmRequest> should match 
// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArm > 
template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmRequest>
{
  static const char* value()
  {
    return DataType< ::slaw_youbot_arm_navigation_srvs::MoveArm >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmResponse> should match 
// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArm > 
template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArm >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmResponse> should match 
// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArm > 
template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmResponse>
{
  static const char* value()
  {
    return DataType< ::slaw_youbot_arm_navigation_srvs::MoveArm >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_MOVEARM_H
