// Generated by gencpp from file slaw_youbot_arm_navigation_srvs/MoveArmIK.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_MOVEARMIK_H
#define SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_MOVEARMIK_H

#include <ros/service_traits.h>


#include <slaw_youbot_arm_navigation_srvs/MoveArmIKRequest.h>
#include <slaw_youbot_arm_navigation_srvs/MoveArmIKResponse.h>


namespace slaw_youbot_arm_navigation_srvs
{

struct MoveArmIK
{

typedef MoveArmIKRequest Request;
typedef MoveArmIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveArmIK
} // namespace slaw_youbot_arm_navigation_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIK > {
  static const char* value()
  {
    return "422de537244f37b21b06e40c0f081e4a";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmIK&) { return value(); }
};

template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIK > {
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_srvs/MoveArmIK";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmIK&) { return value(); }
};


// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIKRequest> should match 
// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIK > 
template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIK >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIKRequest> should match 
// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIK > 
template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIKRequest>
{
  static const char* value()
  {
    return DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIK >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIKResponse> should match 
// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIK > 
template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slaw_youbot_arm_navigation_srvs::MoveArmIK >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIKResponse> should match 
// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIK > 
template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIKResponse>
{
  static const char* value()
  {
    return DataType< ::slaw_youbot_arm_navigation_srvs::MoveArmIK >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::MoveArmIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_MOVEARMIK_H
