// Generated by gencpp from file slaw_youbot_arm_navigation_srvs/SetSide.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_SETSIDE_H
#define SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_SETSIDE_H

#include <ros/service_traits.h>


#include <slaw_youbot_arm_navigation_srvs/SetSideRequest.h>
#include <slaw_youbot_arm_navigation_srvs/SetSideResponse.h>


namespace slaw_youbot_arm_navigation_srvs
{

struct SetSide
{

typedef SetSideRequest Request;
typedef SetSideResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSide
} // namespace slaw_youbot_arm_navigation_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSide > {
  static const char* value()
  {
    return "2b0137ce80ad7b5afacec3c023ec686d";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SetSide&) { return value(); }
};

template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::SetSide > {
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_srvs/SetSide";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SetSide&) { return value(); }
};


// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSideRequest> should match 
// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSide > 
template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSideRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSide >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SetSideRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::SetSideRequest> should match 
// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::SetSide > 
template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::SetSideRequest>
{
  static const char* value()
  {
    return DataType< ::slaw_youbot_arm_navigation_srvs::SetSide >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SetSideRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSideResponse> should match 
// service_traits::MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSide > 
template<>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSideResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slaw_youbot_arm_navigation_srvs::SetSide >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SetSideResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::SetSideResponse> should match 
// service_traits::DataType< ::slaw_youbot_arm_navigation_srvs::SetSide > 
template<>
struct DataType< ::slaw_youbot_arm_navigation_srvs::SetSideResponse>
{
  static const char* value()
  {
    return DataType< ::slaw_youbot_arm_navigation_srvs::SetSide >::value();
  }
  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SetSideResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_SETSIDE_H
