// Generated by gencpp from file slaw_youbot_arm_navigation_srvs/SimpleIkSolverResponse.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_SIMPLEIKSOLVERRESPONSE_H
#define SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_SIMPLEIKSOLVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slaw_youbot_arm_navigation_srvs
{
template <class ContainerAllocator>
struct SimpleIkSolverResponse_
{
  typedef SimpleIkSolverResponse_<ContainerAllocator> Type;

  SimpleIkSolverResponse_()
    : joints()  {
    }
  SimpleIkSolverResponse_(const ContainerAllocator& _alloc)
    : joints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joints_type;
  _joints_type joints;




  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleIkSolverResponse_

typedef ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<std::allocator<void> > SimpleIkSolverResponse;

typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse > SimpleIkSolverResponsePtr;
typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse const> SimpleIkSolverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slaw_youbot_arm_navigation_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slaw_youbot_arm_navigation_msgs': ['/home/ruud/youBot/src/slaw_youbot_arm_navigation/slaw_youbot_arm_navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82c16c802eb7e05fa5331a00ebfb3b28";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82c16c802eb7e05fULL;
  static const uint64_t static_value2 = 0xa5331a00ebfb3b28ULL;
};

template<class ContainerAllocator>
struct DataType< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_srvs/SimpleIkSolverResponse";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joints\n\
";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleIkSolverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slaw_youbot_arm_navigation_srvs::SimpleIkSolverResponse_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_SRVS_MESSAGE_SIMPLEIKSOLVERRESPONSE_H
