# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from slaw_youbot_arm_navigation_srvs/MoveJointsRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import slaw_youbot_arm_navigation_msgs.msg

class MoveJointsRequest(genpy.Message):
  _md5sum = "8a2d91c2b039386c8d06637bd0408986"
  _type = "slaw_youbot_arm_navigation_srvs/MoveJointsRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """slaw_youbot_arm_navigation_msgs/ArmConfiguration configuration
bool blocking
bool velocity_controlled
float32 max_speed

================================================================================
MSG: slaw_youbot_arm_navigation_msgs/ArmConfiguration
float32 arm_joint_1
float32 arm_joint_2
float32 arm_joint_3
float32 arm_joint_4
float32 arm_joint_5"""
  __slots__ = ['configuration','blocking','velocity_controlled','max_speed']
  _slot_types = ['slaw_youbot_arm_navigation_msgs/ArmConfiguration','bool','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       configuration,blocking,velocity_controlled,max_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveJointsRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.configuration is None:
        self.configuration = slaw_youbot_arm_navigation_msgs.msg.ArmConfiguration()
      if self.blocking is None:
        self.blocking = False
      if self.velocity_controlled is None:
        self.velocity_controlled = False
      if self.max_speed is None:
        self.max_speed = 0.
    else:
      self.configuration = slaw_youbot_arm_navigation_msgs.msg.ArmConfiguration()
      self.blocking = False
      self.velocity_controlled = False
      self.max_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5f2Bf.pack(_x.configuration.arm_joint_1, _x.configuration.arm_joint_2, _x.configuration.arm_joint_3, _x.configuration.arm_joint_4, _x.configuration.arm_joint_5, _x.blocking, _x.velocity_controlled, _x.max_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.configuration is None:
        self.configuration = slaw_youbot_arm_navigation_msgs.msg.ArmConfiguration()
      end = 0
      _x = self
      start = end
      end += 26
      (_x.configuration.arm_joint_1, _x.configuration.arm_joint_2, _x.configuration.arm_joint_3, _x.configuration.arm_joint_4, _x.configuration.arm_joint_5, _x.blocking, _x.velocity_controlled, _x.max_speed,) = _struct_5f2Bf.unpack(str[start:end])
      self.blocking = bool(self.blocking)
      self.velocity_controlled = bool(self.velocity_controlled)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5f2Bf.pack(_x.configuration.arm_joint_1, _x.configuration.arm_joint_2, _x.configuration.arm_joint_3, _x.configuration.arm_joint_4, _x.configuration.arm_joint_5, _x.blocking, _x.velocity_controlled, _x.max_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.configuration is None:
        self.configuration = slaw_youbot_arm_navigation_msgs.msg.ArmConfiguration()
      end = 0
      _x = self
      start = end
      end += 26
      (_x.configuration.arm_joint_1, _x.configuration.arm_joint_2, _x.configuration.arm_joint_3, _x.configuration.arm_joint_4, _x.configuration.arm_joint_5, _x.blocking, _x.velocity_controlled, _x.max_speed,) = _struct_5f2Bf.unpack(str[start:end])
      self.blocking = bool(self.blocking)
      self.velocity_controlled = bool(self.velocity_controlled)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5f2Bf = struct.Struct("<5f2Bf")
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from slaw_youbot_arm_navigation_srvs/MoveJointsResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MoveJointsResponse(genpy.Message):
  _md5sum = "a4d50a34d34f18de48e2436ff1472594"
  _type = "slaw_youbot_arm_navigation_srvs/MoveJointsResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool success
string reason

"""
  __slots__ = ['success','reason']
  _slot_types = ['bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveJointsResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.reason is None:
        self.reason = ''
    else:
      self.success = False
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.success))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _struct_B.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.success))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _struct_B.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
class MoveJoints(object):
  _type          = 'slaw_youbot_arm_navigation_srvs/MoveJoints'
  _md5sum = 'd07079461c3693f01c6c76f81e4c199e'
  _request_class  = MoveJointsRequest
  _response_class = MoveJointsResponse
