; Auto-generated. Do not edit!


(cl:in-package slaw_youbot_arm_navigation_actions-msg)


;//! \htmlinclude MoveArmIKFeedback.msg.html

(cl:defclass <MoveArmIKFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveArmIKFeedback (<MoveArmIKFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveArmIKFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveArmIKFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slaw_youbot_arm_navigation_actions-msg:<MoveArmIKFeedback> is deprecated: use slaw_youbot_arm_navigation_actions-msg:MoveArmIKFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveArmIKFeedback>) ostream)
  "Serializes a message object of type '<MoveArmIKFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveArmIKFeedback>) istream)
  "Deserializes a message object of type '<MoveArmIKFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveArmIKFeedback>)))
  "Returns string type for a message object of type '<MoveArmIKFeedback>"
  "slaw_youbot_arm_navigation_actions/MoveArmIKFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveArmIKFeedback)))
  "Returns string type for a message object of type 'MoveArmIKFeedback"
  "slaw_youbot_arm_navigation_actions/MoveArmIKFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveArmIKFeedback>)))
  "Returns md5sum for a message object of type '<MoveArmIKFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveArmIKFeedback)))
  "Returns md5sum for a message object of type 'MoveArmIKFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveArmIKFeedback>)))
  "Returns full string definition for message of type '<MoveArmIKFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveArmIKFeedback)))
  "Returns full string definition for message of type 'MoveArmIKFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveArmIKFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveArmIKFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveArmIKFeedback
))
