; Auto-generated. Do not edit!


(cl:in-package slaw_youbot_arm_navigation_actions-msg)


;//! \htmlinclude MoveArmLinearFeedback.msg.html

(cl:defclass <MoveArmLinearFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveArmLinearFeedback (<MoveArmLinearFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveArmLinearFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveArmLinearFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slaw_youbot_arm_navigation_actions-msg:<MoveArmLinearFeedback> is deprecated: use slaw_youbot_arm_navigation_actions-msg:MoveArmLinearFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveArmLinearFeedback>) ostream)
  "Serializes a message object of type '<MoveArmLinearFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveArmLinearFeedback>) istream)
  "Deserializes a message object of type '<MoveArmLinearFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveArmLinearFeedback>)))
  "Returns string type for a message object of type '<MoveArmLinearFeedback>"
  "slaw_youbot_arm_navigation_actions/MoveArmLinearFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveArmLinearFeedback)))
  "Returns string type for a message object of type 'MoveArmLinearFeedback"
  "slaw_youbot_arm_navigation_actions/MoveArmLinearFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveArmLinearFeedback>)))
  "Returns md5sum for a message object of type '<MoveArmLinearFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveArmLinearFeedback)))
  "Returns md5sum for a message object of type 'MoveArmLinearFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveArmLinearFeedback>)))
  "Returns full string definition for message of type '<MoveArmLinearFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveArmLinearFeedback)))
  "Returns full string definition for message of type 'MoveArmLinearFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveArmLinearFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveArmLinearFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveArmLinearFeedback
))
