; Auto-generated. Do not edit!


(cl:in-package slaw_youbot_arm_navigation_actions-msg)


;//! \htmlinclude VelocityControlledJointTrajectoryFeedback.msg.html

(cl:defclass <VelocityControlledJointTrajectoryFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass VelocityControlledJointTrajectoryFeedback (<VelocityControlledJointTrajectoryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VelocityControlledJointTrajectoryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VelocityControlledJointTrajectoryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slaw_youbot_arm_navigation_actions-msg:<VelocityControlledJointTrajectoryFeedback> is deprecated: use slaw_youbot_arm_navigation_actions-msg:VelocityControlledJointTrajectoryFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VelocityControlledJointTrajectoryFeedback>) ostream)
  "Serializes a message object of type '<VelocityControlledJointTrajectoryFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VelocityControlledJointTrajectoryFeedback>) istream)
  "Deserializes a message object of type '<VelocityControlledJointTrajectoryFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VelocityControlledJointTrajectoryFeedback>)))
  "Returns string type for a message object of type '<VelocityControlledJointTrajectoryFeedback>"
  "slaw_youbot_arm_navigation_actions/VelocityControlledJointTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VelocityControlledJointTrajectoryFeedback)))
  "Returns string type for a message object of type 'VelocityControlledJointTrajectoryFeedback"
  "slaw_youbot_arm_navigation_actions/VelocityControlledJointTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VelocityControlledJointTrajectoryFeedback>)))
  "Returns md5sum for a message object of type '<VelocityControlledJointTrajectoryFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VelocityControlledJointTrajectoryFeedback)))
  "Returns md5sum for a message object of type 'VelocityControlledJointTrajectoryFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VelocityControlledJointTrajectoryFeedback>)))
  "Returns full string definition for message of type '<VelocityControlledJointTrajectoryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VelocityControlledJointTrajectoryFeedback)))
  "Returns full string definition for message of type 'VelocityControlledJointTrajectoryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VelocityControlledJointTrajectoryFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VelocityControlledJointTrajectoryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'VelocityControlledJointTrajectoryFeedback
))
