; Auto-generated. Do not edit!


(cl:in-package slaw_youbot_arm_navigation_actions-msg)


;//! \htmlinclude VelocityControlledJointTrajectoryActionGoal.msg.html

(cl:defclass <VelocityControlledJointTrajectoryActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type slaw_youbot_arm_navigation_actions-msg:VelocityControlledJointTrajectoryGoal
    :initform (cl:make-instance 'slaw_youbot_arm_navigation_actions-msg:VelocityControlledJointTrajectoryGoal)))
)

(cl:defclass VelocityControlledJointTrajectoryActionGoal (<VelocityControlledJointTrajectoryActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VelocityControlledJointTrajectoryActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VelocityControlledJointTrajectoryActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name slaw_youbot_arm_navigation_actions-msg:<VelocityControlledJointTrajectoryActionGoal> is deprecated: use slaw_youbot_arm_navigation_actions-msg:VelocityControlledJointTrajectoryActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <VelocityControlledJointTrajectoryActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader slaw_youbot_arm_navigation_actions-msg:header-val is deprecated.  Use slaw_youbot_arm_navigation_actions-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <VelocityControlledJointTrajectoryActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader slaw_youbot_arm_navigation_actions-msg:goal_id-val is deprecated.  Use slaw_youbot_arm_navigation_actions-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <VelocityControlledJointTrajectoryActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader slaw_youbot_arm_navigation_actions-msg:goal-val is deprecated.  Use slaw_youbot_arm_navigation_actions-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VelocityControlledJointTrajectoryActionGoal>) ostream)
  "Serializes a message object of type '<VelocityControlledJointTrajectoryActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VelocityControlledJointTrajectoryActionGoal>) istream)
  "Deserializes a message object of type '<VelocityControlledJointTrajectoryActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VelocityControlledJointTrajectoryActionGoal>)))
  "Returns string type for a message object of type '<VelocityControlledJointTrajectoryActionGoal>"
  "slaw_youbot_arm_navigation_actions/VelocityControlledJointTrajectoryActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VelocityControlledJointTrajectoryActionGoal)))
  "Returns string type for a message object of type 'VelocityControlledJointTrajectoryActionGoal"
  "slaw_youbot_arm_navigation_actions/VelocityControlledJointTrajectoryActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VelocityControlledJointTrajectoryActionGoal>)))
  "Returns md5sum for a message object of type '<VelocityControlledJointTrajectoryActionGoal>"
  "dbfec08fc63ed03c6015413c957a3208")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VelocityControlledJointTrajectoryActionGoal)))
  "Returns md5sum for a message object of type 'VelocityControlledJointTrajectoryActionGoal"
  "dbfec08fc63ed03c6015413c957a3208")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VelocityControlledJointTrajectoryActionGoal>)))
  "Returns full string definition for message of type '<VelocityControlledJointTrajectoryActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%VelocityControlledJointTrajectoryGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: slaw_youbot_arm_navigation_actions/VelocityControlledJointTrajectoryGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%slaw_youbot_arm_navigation_msgs/ArmConfiguration[] configurations~%float32 max_speed~%~%================================================================================~%MSG: slaw_youbot_arm_navigation_msgs/ArmConfiguration~%float32 arm_joint_1~%float32 arm_joint_2~%float32 arm_joint_3~%float32 arm_joint_4~%float32 arm_joint_5~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VelocityControlledJointTrajectoryActionGoal)))
  "Returns full string definition for message of type 'VelocityControlledJointTrajectoryActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%VelocityControlledJointTrajectoryGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: slaw_youbot_arm_navigation_actions/VelocityControlledJointTrajectoryGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%slaw_youbot_arm_navigation_msgs/ArmConfiguration[] configurations~%float32 max_speed~%~%================================================================================~%MSG: slaw_youbot_arm_navigation_msgs/ArmConfiguration~%float32 arm_joint_1~%float32 arm_joint_2~%float32 arm_joint_3~%float32 arm_joint_4~%float32 arm_joint_5~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VelocityControlledJointTrajectoryActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VelocityControlledJointTrajectoryActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'VelocityControlledJointTrajectoryActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
