// Generated by gencpp from file slaw_youbot_arm_navigation_msgs/ArmConfiguration.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_MSGS_MESSAGE_ARMCONFIGURATION_H
#define SLAW_YOUBOT_ARM_NAVIGATION_MSGS_MESSAGE_ARMCONFIGURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slaw_youbot_arm_navigation_msgs
{
template <class ContainerAllocator>
struct ArmConfiguration_
{
  typedef ArmConfiguration_<ContainerAllocator> Type;

  ArmConfiguration_()
    : arm_joint_1(0.0)
    , arm_joint_2(0.0)
    , arm_joint_3(0.0)
    , arm_joint_4(0.0)
    , arm_joint_5(0.0)  {
    }
  ArmConfiguration_(const ContainerAllocator& _alloc)
    : arm_joint_1(0.0)
    , arm_joint_2(0.0)
    , arm_joint_3(0.0)
    , arm_joint_4(0.0)
    , arm_joint_5(0.0)  {
  (void)_alloc;
    }



   typedef float _arm_joint_1_type;
  _arm_joint_1_type arm_joint_1;

   typedef float _arm_joint_2_type;
  _arm_joint_2_type arm_joint_2;

   typedef float _arm_joint_3_type;
  _arm_joint_3_type arm_joint_3;

   typedef float _arm_joint_4_type;
  _arm_joint_4_type arm_joint_4;

   typedef float _arm_joint_5_type;
  _arm_joint_5_type arm_joint_5;




  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> const> ConstPtr;

}; // struct ArmConfiguration_

typedef ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<std::allocator<void> > ArmConfiguration;

typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration > ArmConfigurationPtr;
typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration const> ArmConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slaw_youbot_arm_navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slaw_youbot_arm_navigation_msgs': ['/home/ruud/youBot/src/slaw_youbot_arm_navigation/slaw_youbot_arm_navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4002ce9c0c27afe7b7ffe45719b55098";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4002ce9c0c27afe7ULL;
  static const uint64_t static_value2 = 0xb7ffe45719b55098ULL;
};

template<class ContainerAllocator>
struct DataType< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_msgs/ArmConfiguration";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 arm_joint_1\n\
float32 arm_joint_2\n\
float32 arm_joint_3\n\
float32 arm_joint_4\n\
float32 arm_joint_5\n\
";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_joint_1);
      stream.next(m.arm_joint_2);
      stream.next(m.arm_joint_3);
      stream.next(m.arm_joint_4);
      stream.next(m.arm_joint_5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmConfiguration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slaw_youbot_arm_navigation_msgs::ArmConfiguration_<ContainerAllocator>& v)
  {
    s << indent << "arm_joint_1: ";
    Printer<float>::stream(s, indent + "  ", v.arm_joint_1);
    s << indent << "arm_joint_2: ";
    Printer<float>::stream(s, indent + "  ", v.arm_joint_2);
    s << indent << "arm_joint_3: ";
    Printer<float>::stream(s, indent + "  ", v.arm_joint_3);
    s << indent << "arm_joint_4: ";
    Printer<float>::stream(s, indent + "  ", v.arm_joint_4);
    s << indent << "arm_joint_5: ";
    Printer<float>::stream(s, indent + "  ", v.arm_joint_5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_MSGS_MESSAGE_ARMCONFIGURATION_H
