// Generated by gencpp from file slaw_youbot_arm_navigation_msgs/EndeffectorPosition.msg
// DO NOT EDIT!


#ifndef SLAW_YOUBOT_ARM_NAVIGATION_MSGS_MESSAGE_ENDEFFECTORPOSITION_H
#define SLAW_YOUBOT_ARM_NAVIGATION_MSGS_MESSAGE_ENDEFFECTORPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace slaw_youbot_arm_navigation_msgs
{
template <class ContainerAllocator>
struct EndeffectorPosition_
{
  typedef EndeffectorPosition_<ContainerAllocator> Type;

  EndeffectorPosition_()
    : position()
    , angle(0.0)  {
    }
  EndeffectorPosition_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> const> ConstPtr;

}; // struct EndeffectorPosition_

typedef ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<std::allocator<void> > EndeffectorPosition;

typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition > EndeffectorPositionPtr;
typedef boost::shared_ptr< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition const> EndeffectorPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slaw_youbot_arm_navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'slaw_youbot_arm_navigation_msgs': ['/home/ruud/youBot/src/slaw_youbot_arm_navigation/slaw_youbot_arm_navigation_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd328302c3e9f205aea6bb65211e73fa";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd328302c3e9f205ULL;
  static const uint64_t static_value2 = 0xaea6bb65211e73faULL;
};

template<class ContainerAllocator>
struct DataType< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slaw_youbot_arm_navigation_msgs/EndeffectorPosition";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
float32 angle\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndeffectorPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slaw_youbot_arm_navigation_msgs::EndeffectorPosition_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAW_YOUBOT_ARM_NAVIGATION_MSGS_MESSAGE_ENDEFFECTORPOSITION_H
